INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_ADMIN');
INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_ADMIN_TP');
INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_USUARIO');

INSERT INTO tb_usuario (nome, email, login, password, user_state, first_access, user_uuid, termo_parceria) VALUES ('Hassan Kuntze', 'hassankrc@ctcea.org.br', 'hassankrc', '$2a$10$x6lljObKIzpQXgW5sMSwduYKOJ8OM3EgzORMbXkMh2iX7.jdczWFq', 1, 1, '72eafc15-9f68-4379-9f5a-d2bdaa81325a', 'CCOMGEX');
INSERT INTO tb_usuario (nome, email, login, password, user_state, first_access, user_uuid, termo_parceria) VALUES ('Ewaldo Alves Filho', 'ewaldoaf@ctcea.org.br', 'fota', '$2a$10$zvnu3816MLSW9eqFpieTtOj/L/DWrrEM32BwTghqWXmgYugoaORmW', 1, 1, '8528c672-3ca3-42c8-a03d-6b32445acfd8', 'DECEA');

INSERT INTO tb_perfil_usuario (id_usuario, id_perfil) VALUES (1, 1);
INSERT INTO tb_perfil_usuario (id_usuario, id_perfil) VALUES (2, 3);

INSERT INTO tb_fornecedor (nome) VALUES ('Easytech Informática e Serviços LTDA EPP');
INSERT INTO tb_fornecedor (nome) VALUES ('VLF Máquinas e Soluções Empresariais LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Super Clima Com. Var. de Equip. de Ref. Ar Cond. - ME');
INSERT INTO tb_fornecedor (nome) VALUES ('Martins Requinte Comercio de Moveis Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Valentino Moveis Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Wood Center Comercio Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Frigelar Comercio e Industria LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Fujioka Eletro Imagem S.A.');
INSERT INTO tb_fornecedor (nome) VALUES ('Controltech Controle De Ponto De Acesso, Informática E Eletrônicos LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('DELL Computadores do Brasil LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('NETSCIENCE TECNOLOGIA LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Bytes Informática e Tecnologia LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('Barra Serviços de Construção e Engenharia Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Brasfreezer Refrigeração e Serviços Ltda');
INSERT INTO tb_fornecedor (nome) VALUES ('G.A. Elias - ME');
INSERT INTO tb_fornecedor (nome) VALUES ('Ferramentas Prof. E Equip. De Seg. Ltda (Rede EPI)');
INSERT INTO tb_fornecedor (nome) VALUES ('Claro S/A');
INSERT INTO tb_fornecedor (nome) VALUES ('CGK SISTAMAS DE INFORMAÇÃO LTDA - AF090/22');
INSERT INTO tb_fornecedor (nome) VALUES ('E-SEC TECNOLOGIA - OS124/22');
INSERT INTO tb_fornecedor (nome) VALUES ('CGK SISTAMAS DE INFORMAÇÃO LTDA - OS137/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS143/22');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS068/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS071/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS058/22');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS009/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS076/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS002/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS176/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS063/23');
INSERT INTO tb_fornecedor (nome) VALUES ('TARGETWARE INFORMÁTICA - OS120/22');
INSERT INTO tb_fornecedor (nome) VALUES ('Telefonica Brasil - OS094-22');
INSERT INTO tb_fornecedor (nome) VALUES ('Telefonica Brasil - OS132/22');
INSERT INTO tb_fornecedor (nome) VALUES ('Positivo Distribuição - OS139/24');
INSERT INTO tb_fornecedor (nome) VALUES ('Wimpress Outsourcing - CT002/25');
INSERT INTO tb_fornecedor (nome) VALUES ('3eX Comercio - CT09/22');

INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('07/2023', 'Contrato de equipamentos de informática firmado em 07/2023', '2023-07-01', '2026-07-01', 0, 19);
INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('05/2021', 'Contrato de licenças de software firmado em 05/2021', '2021-05-15', '2027-05-15', 0, 21);
INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('11/2024', 'Contrato de licenças de software adicional firmado em 11/2024', '2024-11-21', '2025-11-21', 0, 23);

INSERT INTO tb_area (nome, responsavel) VALUES ('GTI', 'ARMANDO FURLAN JUNIOR');
INSERT INTO tb_area (nome, responsavel) VALUES ('GAP', 'MARCUS VINICIUS MENDONCA PIRES');
INSERT INTO tb_area (nome, responsavel) VALUES ('GPS', 'EDNI DE CASTRO PARANHOS');

INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário', null);

INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reuniões SR1', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala GID', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala GPS', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala Servidor', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reuniões - PTTC', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sala de reunião - SR1 Interna', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala GAP/ CAP. / T.I', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala SLI/ CAP. / T.I', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala CTCEA - Antiga A3J', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reunião 2', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GTI - Sala de Reunião', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala Equipe Gestão patrimonial', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da STI', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sala 2 pavimento - Clog', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Acesso ao alojamento dos militares', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reuniões CTCEA', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GAP', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GTI', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Corredor', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Sala Asse. PJT.', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Sala STI', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala DM7', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Auditório', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Adriano Alvares da Silva', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Elen Aparecida Nunes dos Santos', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Flavio de Carvalho Pinheiro', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Francislei Vilela', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Glauco Bueno da Silva', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Isaack Correia Machado', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Ricardo Nobrega Guimarães', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Walter Mauricio Perrella', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Armario sala GPS', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - SAP - Roberto Gomes', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - STI - Anderson', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - GAP - Marcus Pires', 2);

INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('DISPONÍVEL PARA UTILIZAÇÃO', null, null);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('INSTALADO NO DISPOSITIVO', null, null);

INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ADRIANO ALVARES DA SILVA', 'adrianosilva@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ANA KEILLA SARAIVA DE SOUZA NERY', 'anaaks@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ANA TEREZA VARANDAS FERREIRA', 'anavarandas@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ANDERSON FERNANDES DE MENESES SILVA', 'andersonmeneses@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ANDERSON TESCH HOSKEN ALVARENGA', 'andersonhosken@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ANDREIA SANTIAGO DE OLIVEIRA', 'andreiasantiago@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ARMANDO FURLAN JUNIOR', 'armandoafj@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('BRUNA MONIQUE OLIVEIRA ROCHA', 'brunabmo@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('CAINA FELIPE BENTO RAZZOLINI', 'cainarazzolini@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('CARLOS HENRIQUE MAGALHAES DUHAU', 'carloshenrique@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('CHEISTON DE FIGUEIREDO SENA', 'cheistonfigueiredo@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('CLEITON JOSE FELIPE', 'cleitonfelipe@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('CLEVERSON CARVALHO DE OLIVEIRA', 'cleversoncarvalho@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('DIORINESSE SANTANA DA SILVA', 'diorinesse@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EDNI DE CASTRO PARANHOS', 'edni@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EDUARDO ARUME', 'eduardoea@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ELEN APARECIDA NUNES DOS SANTOS', 'elenean@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ELESSANDRA CRISTINI DELGADO GIMENES', 'elessandradelgado@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EMANUEL JONATA OLIVEIRA DE BRITO', 'emanuelbrito@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ERICO DE OLIVEIRA BORGES', 'ericoborges@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EVERTON NETTO AMANDIO', 'evertonamandio@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EVIANE ALEXANDRA CARDOSO', 'eviane.cardoso@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('EWALDO ALVES DA SILVA FILHO', 'ewaldoeas@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('FABIANE COUTO MUNHOZ', 'fabianefcm@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('FLAVIA HELENA REGIS FERNANDES', 'flaviafernandes@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('FLAVIO DE CARVALHO PINHEIRO', 'flaviopinheiro@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('FRANCISLEI VILELA', 'francisleivilela@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('GEORGIA GUEDES BOAVENTURA', 'georgiaboaventura@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('GIULLIANO GONCALVES CONDE', 'giullianoconde@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('GLAUCO BUENO DA SILVA', 'glauco.silva@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('HASSAN KUNTZE RODRIGUES DA CUNHA', 'hassankrc@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ISAACK CORREA MACHADO', 'isaackmachado@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('JOÃO CLAUDIO DE ALMEIDA ILDEFONSO', 'joaojca@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('LAUDICEIA EMERICK', 'laudiceiale@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('LEANDRO DA SILVA CHAMPOSKI', 'leandrochamposki@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MARCELO FARIAS DE CARVALHO', 'marcelofarias@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MARCIA ADJUTO BOAVENTURA ABRITTA AGUIAR', 'marciaboaventura@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MARCUS VINICIUS ARAGÃO DE CAMPOS', 'marcusvinicius@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MARCUS VINICIUS MENDONÇA PIRES', 'marcuspires@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MAURICIO ABE MACHADO', 'mauricioabe@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MAURICIO HOFMAM DA SILVA', 'mauriciohofmam@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('MONICA DO NASCIMENTO FONSECA', 'monicafonseca@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('NADIA GOUVEA ANDREZO CARNEIRO', 'nadiagouvea@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('NEIDE DE FATIMA RESENDE', 'neideresende@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('OSWALDO HIPOLITO DE ALMEIDA JUNIOR', 'oswaldohipolito@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('PEDRO EDUARDO DE SOUZA DIAS', 'pedrodias@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('RAMON LARCHER MOREIRA', 'ramonmoreira@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('RICARDO NOBREGA GUIMARAES', 'ricardonobrega@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('ROBERTO WAGNER GOMES', 'robertogomes@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('RONALDO BARBOSA DA SILVEIRA', 'ronaldosilveira@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('THIAGO VALERIANO ARAUJO DA SILVA', 'thiagosilva@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('TIAGO CAMELO DA ASSUNÇÃO', 'tiagoassuncao@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('UBIRAJARA RIBEIRO DE CARVALHO', 'ubirajaracarvalho@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('VERA LUCIA DEMOLINER', 'verademoliner@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('WALTER MAURICIO PERRELLA', 'walterperrella@ctcea.org.br', 1);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('WEBSTER S GOMES FERNANDES', 'webstersfernandes@ctcea.org.br', 3);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('WELLINGTON DIONE DE FREITAS NASCIMENTO', 'wellingtonnascimento@ctcea.org.br', 2);
INSERT INTO tb_usuario_responsavel (nome, email, id_area) VALUES ('WGLEYBSON MENDES MARTINS', 'wgleybsonmartins@ctcea.org.br', 2);