INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_ADMIN');
INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_ANALISTA_INVENTARIO');
INSERT INTO tb_perfil (autorizacao) VALUES ('PERFIL_USUARIO');

INSERT INTO tb_usuario (nome, email, login, password, user_state, first_access, user_uuid, termo_parceria) VALUES ('Hassan Kuntze', 'hassankrc@ctcea.org.br', 'hassankrc', '$2a$10$x6lljObKIzpQXgW5sMSwduYKOJ8OM3EgzORMbXkMh2iX7.jdczWFq', 1, 1, '72eafc15-9f68-4379-9f5a-d2bdaa81325a', 'CCOMGEX');
INSERT INTO tb_usuario (nome, email, login, password, user_state, first_access, user_uuid, termo_parceria) VALUES ('Ewaldo Alves Filho', 'ewaldoaf@ctcea.org.br', 'fota', '$2a$10$zvnu3816MLSW9eqFpieTtOj/L/DWrrEM32BwTghqWXmgYugoaORmW', 1, 1, '8528c672-3ca3-42c8-a03d-6b32445acfd8', 'DECEA');

INSERT INTO tb_perfil_usuario (id_usuario, id_perfil) VALUES (1, 1);
INSERT INTO tb_perfil_usuario (id_usuario, id_perfil) VALUES (2, 3);

INSERT INTO tb_fornecedor (nome) VALUES ('Easytech Informática e Serviços LTDA EPP');
INSERT INTO tb_fornecedor (nome) VALUES ('VLF Máquinas e Soluções Empresariais LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Super Clima Com. Var. de Equip. de Ref. Ar Cond. - ME');
INSERT INTO tb_fornecedor (nome) VALUES ('Martins Requinte Comercio de Moveis Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Valentino Moveis Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Wood Center Comercio Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Frigelar Comercio e Industria LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Fujioka Eletro Imagem S.A.');
INSERT INTO tb_fornecedor (nome) VALUES ('Controltech Controle De Ponto De Acesso, Informática E Eletrônicos LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('DELL Computadores do Brasil LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('NETSCIENCE TECNOLOGIA LTDA');
INSERT INTO tb_fornecedor (nome) VALUES ('Bytes Informática e Tecnologia LTDA.');
INSERT INTO tb_fornecedor (nome) VALUES ('Barra Serviços de Construção e Engenharia Ltda.');
INSERT INTO tb_fornecedor (nome) VALUES ('Brasfreezer Refrigeração e Serviços Ltda');
INSERT INTO tb_fornecedor (nome) VALUES ('G.A. Elias - ME');
INSERT INTO tb_fornecedor (nome) VALUES ('Ferramentas Prof. E Equip. De Seg. Ltda (Rede EPI)');
INSERT INTO tb_fornecedor (nome) VALUES ('Claro S/A');
INSERT INTO tb_fornecedor (nome) VALUES ('CGK SISTAMAS DE INFORMAÇÃO LTDA - AF090/22');
INSERT INTO tb_fornecedor (nome) VALUES ('E-SEC TECNOLOGIA - OS124/22');
INSERT INTO tb_fornecedor (nome) VALUES ('CGK SISTAMAS DE INFORMAÇÃO LTDA - OS137/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS143/22');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS068/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS071/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS058/22');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS009/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS076/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS002/25');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS176/24');
INSERT INTO tb_fornecedor (nome) VALUES ('MYCERT SOLUCOES DIGITAIS LTDA - OS063/23');
INSERT INTO tb_fornecedor (nome) VALUES ('TARGETWARE INFORMÁTICA - OS120/22');
INSERT INTO tb_fornecedor (nome) VALUES ('Telefonica Brasil - OS094-22');
INSERT INTO tb_fornecedor (nome) VALUES ('Telefonica Brasil - OS132/22');
INSERT INTO tb_fornecedor (nome) VALUES ('Positivo Distribuição - OS139/24');
INSERT INTO tb_fornecedor (nome) VALUES ('Wimpress Outsourcing - CT002/25');
INSERT INTO tb_fornecedor (nome) VALUES ('3eX Comercio - CT09/22');

INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('07/2023', 'Contrato de equipamentos de informática firmado em 07/2023', '2023-07-01', '2026-07-01', 0, 19);
INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('05/2021', 'Contrato de licenças de software firmado em 05/2021', '2021-05-15', '2027-05-15', 0, 21);
INSERT INTO tb_contrato (titulo, descricao, inicio_data_vigencia, fim_data_vigencia, termo_parceria, id_fornecedor) VALUES ('11/2024', 'Contrato de licenças de software adicional firmado em 11/2024', '2024-11-21', '2025-11-21', 0, 23);

INSERT INTO tb_area (nome, responsavel, substituto_responsavel) VALUES ('GTI', 'ARMANDO FURLAN JUNIOR', null);
INSERT INTO tb_area (nome, responsavel, substituto_responsavel) VALUES ('GAP', 'MARCUS VINICIUS MENDONCA PIRES', null);
INSERT INTO tb_area (nome, responsavel, substituto_responsavel) VALUES ('GPS', 'EDNI DE CASTRO PARANHOS', 'MAURICIO ABE MACHADO');

INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário ', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário ', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Vinculado ao perfil do usuário ', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reuniões SR1', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala GID', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala GPS', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala Servidor', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sala de reunião - SR1 Interna', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala SLI/ CAP. / T.I', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala CTCEA - Antiga A3J', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reunião 2', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GTI - Sala de Reunião', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala Equipe Gestão patrimonial', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da STI', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sala 2 pavimento - Clog', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Acesso ao alojamento dos militares', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala de Reuniões CTCEA', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GAP', 2);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala da GTI', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Corredor', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Sala Asse. PJT.', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Predio ComDCiber - Sala STI', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Sala DM7', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Auditório', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Adriano Alvares da Silva', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Elen Aparecida Nunes dos Santos', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Flavio de Carvalho Pinheiro', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Francislei Vilela', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Glauco Bueno da Silva', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Isaack Correia Machado', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Ricardo Nobrega Guimarães', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Sob responsabilidade do empregado Walter Mauricio Perrella', 1);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - Armario sala GPS', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - SAP - Roberto Gomes', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - STI - Anderson', 3);
INSERT INTO tb_localizacao (nome, id_area) VALUES ('Prédio ComDCiber - GAP - Marcus Pires', 2);

INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ADRIANO ALVARES DA SILVA', 'adriano_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ANA KEILLA SARAIVA DE SOUZA NERY', 'ana_nery@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ANA TEREZA VARANDAS FERREIRA', 'ana_ferreira@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ANDERSON FERNANDES DE M. SILVA', 'anderson_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ANDERSON TESCH HOSKEN ALVARENGA', 'anderson_alvarenga@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ANDREIA SANTIAGO DE OLIVEIRA', 'andreia_oliveira@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ARMANDO FURLAN JUNIOR', 'armando_junior@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('BRUNA MONIQUE OLIVEIRA ROCHA', 'bruna_rocha@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('CAINA FELIPE BENTO RAZZOLINI', 'caina_razzolini@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('CARLOS HENRIQUE MAGALHAES DUHAU', 'carlos_duhau@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('CHEISTON DE FIGUEIREDO SENA', 'cheiston_sena@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('CLEITON JOSE FELIPE', 'cleiton_felipe@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('CLEVERSON CARVALHO DE OLIVEIRA', 'cleverson_oliveira@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('DIORINESSE SANTANA DA SILVA', 'diorinesse_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EDNI DE CASTRO PARANHOS', 'edni_paranhos@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EDUARDO ARUME', 'eduardo_arume@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ELEN APARECIDA NUNES DOS SANTOS', 'elen_santos@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ELESSANDRA CRISTINI DELGADO GIMENES', 'elessandra_gimenes@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EMANUEL JONATA OLIVEIRA DE BRITO', 'emanuel_brito@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ERICO DE OLIVEIRA BORGES', 'erico_borges@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EVERTON NETTO AMANDIO', 'everton_amandio@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EVIANE ALEXANDRA CARDOSO', 'eviane_cardoso@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('EWALDO ALVES DA SILVA FILHO', 'ewaldo_filho@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('FABIANE COUTO MUNHOZ', 'fabiane_munhoz@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('FLAVIA HELENA REGIS FERNANDES', 'flavia_fernandes@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('FLAVIO DE CARVALHO PINHEIRO', 'flavio_pinheiro@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('FRANCISLEI VILELA', 'francislei_vilela@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('GEORGIA GUEDES BOAVENTURA', 'georgia_boaventura@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('GIULLIANO GONCALVES CONDE', 'giulliano_conde@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('GLAUCO BUENO DA SILVA', 'glauco_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('HASSAN KUNTZE RODRIGUES DA CUNHA', 'hassan_cunha@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ISAACK CORREA MACHADO', 'isaack_machado@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('JOAO CLAUDIO DE ALMEIDA ILDEFONSO', 'joao_ildefonso@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('LAUDICEIA EMERICK', 'laudiceia_emerick@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('LEANDRO DA SILVA CHAMPOSKI', 'leandro_champoski@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MARCELO FARIAS DE CARVALHO', 'marcelo_carvalho@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MARCIA ADJUTO BOAVENTURA ABRITTA AGUIAR', 'marcia_aguiar@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MARCUS VINICIUS ARAGAO DE CAMPOS', 'marcus_campos@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MARCUS VINICIUS MENDONCA PIRES', 'marcus_pires@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MAURICIO ABE MACHADO', 'mauricio_machado@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('MAURICIO HOFMAM DA SILVA', 'mauricio_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('NADIA GOUVEA ANDREZO CARNEIRO', 'nadia_carneiro@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('OSWALDO HIPOLITO DE ALMEIDA JUNIOR', 'oswaldo_junior@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('PEDRO EDUARDO DE SOUSA DIAS', 'pedro_dias@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('RAMON LARCHER MOREIRA', 'ramon_moreira@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('RICARDO NOBREGA GUIMARAES', 'ricardo_guimaraes@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('ROBERTO WAGNER GOMES', 'roberto_gomes@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('RONALDO BARBOSA DA SILVEIRA', 'ronaldo_silveira@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('THIAGO VALERIANO ARAUJO DA SILVA', 'thiago_silva@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('UBIRAJARA RIBEIRO DE CARVALHO', 'ubirajara_carvalho@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('VERA LUCIA DEMOLINER', 'vera_demoliner@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('WALTER MAURICIO PERRELLA', 'walter_perrella@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('WEBSTER S GOMES FERNANDES', 'webster_fernandes@dominio.com');
INSERT INTO tb_usuario_responsavel (nome, email) VALUES ('WELLINGTON DIONE DE FREITAS NASCIMENTO', 'wellington_nascimento@dominio.com');

INSERT INTO tb_ativo_tangivel (id, id_patrimonial, categoria, descricao, id_area, data_aquisicao, codigo_serie, observacoes, id_usuario_responsavel, estado_conservacao, gerar_id_patrimonial, id_localizacao, desabilitado, razao_desabilitado, id_fornecedor, id_contrato, termo_parceria) VALUES (NEXT VALUE FOR hibernate_sequence, '1676', 1, 'Smart TV 75” 4K LED, Marca TCL, modelo 75P735 VA.', 2, '2023-04-06', '941463B306AA000577', null, 14, 'Novo', 0, 10, 0, null, 1, null, 'CCOMGEX');
INSERT INTO tb_ativo_intangivel (id, id_patrimonial, categoria, descricao, id_area, data_aquisicao, codigo_serie, observacoes, id_usuario_responsavel, gerar_id_patrimonial, id_localizacao, desabilitado, razao_desabilitado, id_fornecedor, id_contrato, termo_parceria) VALUES (NEXT VALUE FOR hibernate_sequence, 'CCOMGEX/0BAC12', 5, 'Microsoft Office 365 Business Standard Ativação On-Line 55', 3, '2022-11-11', 'Ativação realizada na Nuvem', null, 1, 0, 2, 0, null, 18, 1, 'CCOMGEX');
INSERT INTO tb_ativo_tangivel_locacao (id, id_patrimonial, categoria, descricao, id_area, data_aquisicao, codigo_serie, observacoes, id_usuario_responsavel, estado_conservacao, gerar_id_patrimonial, id_localizacao, desabilitado, razao_desabilitado, data_devolucao_prevista, data_devolucao_realizada, id_fornecedor, id_contrato, termo_parceria) VALUES (NEXT VALUE FOR hibernate_sequence, 'CCOMGEX/2GEMGC', 3, 'OptiPlex 5000 Small Form Factor - Dell', 1, '2022-09-01', 'BW3D6R3', null, 54, 'Novo', 0, 28, 0, null, '2025-11-05', null, 31, 2, 'CCOMGEX');
INSERT INTO tb_ativo_tangivel_locacao (id, id_patrimonial, categoria, descricao, id_area, data_aquisicao, codigo_serie, observacoes, id_usuario_responsavel, estado_conservacao, gerar_id_patrimonial, id_localizacao, desabilitado, razao_desabilitado, data_devolucao_prevista, data_devolucao_realizada, id_fornecedor, id_contrato, termo_parceria) VALUES (NEXT VALUE FOR hibernate_sequence, 'CCOMGEX/EX812A', 3, 'ThinkCentre Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz 1.99 GHz - Lenovo', 2, '2022-10-26', 'PE09N14N', null, 39, 'Novo', 0, 28, 0, null, '2025-12-06', null, 32, 2, 'CCOMGEX');